runtime: nodejs10
env_variables:
  NODE_ENV: production

handlers:

  - url: /image_library/
    static_files: dist/index.html
    upload: dist/index.html
  - url: /image_library/
    static_dir: dist

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE