steps:
  # Install node packages
  - name: "gcr.io/image-library-338318/npm"
    args: ["install"]
    dir: "image_library"

  # Build production package
  - name: "gcr.io/image-library-338318/ng"
    args: [ 'run', 'build', '--prod' ]

  # Deploy to google cloud app engine
  - name: "gcr.io/image-library-338318/gcloud"
    args: ["app", "deploy", "--version=prod"]
