steps:
  # Install node packages
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
    dir: "image_library"

  # Build production package
  - name: "gcr.io/image-library-338318/ng"
    args: ["build", "--prod"]
    dir: "dist"

  # Deploy to google cloud app engine
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "--version=prod"]
    dir: "image_library"